trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests=true'

# Step 2: Test
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Unit Test Results'

# Step 3: Reports
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify'

# Step 4: Publish Coverage
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '**/jacoco.xml'
